server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: git,vault
  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: myroot
          kv-version: 2
          backend: secret
          profile-separator: /
        git:
          uri: ${GH_URL}
          username: ${GH_USER}
          password: ${GH_TOKEN}
          default-label: main
          search-paths: "/**"
        native:
          search-locations:
            - file:/Users/oudom/Documents/ITP/itp-microservices/itp-config-repo/
            - file:/Users/oudom/Documents/ITP/itp-microservices/itp-config-repo/{application}/